apiVersion: apps/v1
kind: Deployment
metadata:
  name: boomi-molecule
  namespace: boomi-runtime
  labels:
    app.kubernetes.io/name: boomi-molecule
    app.kubernetes.io/component: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: boomi-molecule
  template:
    metadata:
      labels:
        app.kubernetes.io/name: boomi-molecule
        app.kubernetes.io/component: runtime
    spec:
      serviceAccountName: boomi-molecule-sa
      terminationGracePeriodSeconds: 300
      containers:
        - name: boomi-molecule
          image: boomi/molecule:latest
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 8080
              name: web
            - containerPort: 1099
              name: jmx
          env:
            - name: ATOM_LOCALHOSTID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/tmp/jmx_prometheus_javaagent-0.20.0.jar=1099:/tmp/jmx-config.yaml"
            - name: BOOMI_ATOMNAME
              valueFrom:
                secretKeyRef:
                  name: boomi-secrets
                  key: BOOMI_ATOMNAME
            - name: BOOMI_ACCOUNTID
              valueFrom:
                secretKeyRef:
                  name: boomi-secrets
                  key: BOOMI_ACCOUNTID
            - name: INSTALL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: boomi-secrets
                  key: INSTALL_TOKEN
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
            limits:
              cpu: 1000m
              memory: 6Gi
          volumeMounts:
            - name: boomi-data
              mountPath: /mnt/boomi
          livenessProbe:
            httpGet:
              path: /_admin/liveness
              port: 9090
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_admin/readiness
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - /opt/scripts/node_offboard.sh
      volumes:
        - name: boomi-data
          persistentVolumeClaim:
            claimName: boomi-storage
