# Boomi Runtime Configuration
# Edit these values for your deployment

# Basic configuration
project:
  name: boomi-molecule
  namespace: boomi-runtime

# Container image
image:
  repository: boomi/molecule
  tag: latest

# Resources
resources:
  requests:
    cpu: 500m
    memory: 4Gi
  limits:
    cpu: 1000m
    memory: 6Gi

# Storage
storage:
  size: 10Gi
  storageClass: ""

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70
  targetMemoryUtilization: 80
