# Example Kubernetes secrets for Boomi deployment
# DO NOT commit actual secrets to version control

apiVersion: v1
kind: Secret
metadata:
  name: boomi-secrets
  namespace: boomi-runtime
type: Opaque
stringData:
  # Boomi Platform Configuration
  BOOMI_ACCOUNTID: "your-boomi-account-id"
  BOOMI_ATOMNAME: "your-atom-name" 
  INSTALL_TOKEN: "your-molecule-install-token"
  
  # Boomi API Configuration (for node offboarding)
  BOOMI_USERNAME: "TOKEN.your-api-user@your-domain.com"
  BOOMI_PASSWORD: "your-api-password"
  BOOMI_ATOM_ID: "your-atom-uuid"
  BOOMI_BASE_URL: "https://api.boomi.com"

---
# Example: Create secrets from command line instead
# kubectl create secret generic boomi-secrets \
#   --from-literal=BOOMI_ACCOUNTID="your-account-id" \
#   --from-literal=BOOMI_ATOMNAME="your-atom-name" \
#   --from-literal=INSTALL_TOKEN="your-install-token" \
#   --from-literal=BOOMI_PASSWORD="your-password" \
#   --from-literal=BOOMI_ATOM_ID="your-atom-id" \
#   --from-literal=BOOMI_USERNAME="your-username" \
#   --from-literal=BOOMI_BASE_URL="https://api.boomi.com" \
#   -n boomi-runtime
