apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boomi-storage
  namespace: boomi-dev
  labels:
    app.kubernetes.io/name: boomi-molecule-dev
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
