apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boomi-molecule-dev-hpa
  namespace: boomi-dev
  labels:
    app.kubernetes.io/name: boomi-molecule-dev
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boomi-molecule-dev
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
